// GENERATED by `npm run db:types` (supabase gen types typescript --local). Do not edit.
// Source of truth: supabase/migrations. Human page: docs/CONTRACT.md.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      crm_issues: {
        Row: {
          created_at: string
          detail: string | null
          id: string
          job_id: string | null
          kind: string
          resolved_at: string | null
          status: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: string
          job_id?: string | null
          kind: string
          resolved_at?: string | null
          status?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: string
          job_id?: string | null
          kind?: string
          resolved_at?: string | null
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "crm_issues_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      crm_notes: {
        Row: {
          author: string | null
          body: string
          created_at: string
          enquiry_id: string | null
          id: string
          user_id: string | null
        }
        Insert: {
          author?: string | null
          body: string
          created_at?: string
          enquiry_id?: string | null
          id?: string
          user_id?: string | null
        }
        Update: {
          author?: string | null
          body?: string
          created_at?: string
          enquiry_id?: string | null
          id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "crm_notes_enquiry_id_fkey"
            columns: ["enquiry_id"]
            isOneToOne: false
            referencedRelation: "enquiries"
            referencedColumns: ["id"]
          },
        ]
      }
      crm_tasks: {
        Row: {
          created_at: string
          done_at: string | null
          due_on: string | null
          enquiry_id: string | null
          id: string
          owner: string | null
          title: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          done_at?: string | null
          due_on?: string | null
          enquiry_id?: string | null
          id?: string
          owner?: string | null
          title: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          done_at?: string | null
          due_on?: string | null
          enquiry_id?: string | null
          id?: string
          owner?: string | null
          title?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "crm_tasks_enquiry_id_fkey"
            columns: ["enquiry_id"]
            isOneToOne: false
            referencedRelation: "enquiries"
            referencedColumns: ["id"]
          },
        ]
      }
      email_log: {
        Row: {
          id: string
          job_id: string | null
          provider_id: string | null
          sent_at: string
          slug: string
          to_email: string
          user_id: string | null
        }
        Insert: {
          id?: string
          job_id?: string | null
          provider_id?: string | null
          sent_at?: string
          slug: string
          to_email: string
          user_id?: string | null
        }
        Update: {
          id?: string
          job_id?: string | null
          provider_id?: string | null
          sent_at?: string
          slug?: string
          to_email?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "email_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      enquiries: {
        Row: {
          catalogue_size: string | null
          company: string | null
          created_at: string
          email: string
          handled: boolean
          handled_at: string | null
          id: string
          message: string | null
          name: string
          referrer: string | null
          rel_owner: string | null
          rel_status: string | null
          role: string
          source: string | null
          target_languages: string[] | null
          unlocked_audio: boolean
          user_agent: string | null
        }
        Insert: {
          catalogue_size?: string | null
          company?: string | null
          created_at?: string
          email: string
          handled?: boolean
          handled_at?: string | null
          id?: string
          message?: string | null
          name: string
          referrer?: string | null
          rel_owner?: string | null
          rel_status?: string | null
          role: string
          source?: string | null
          target_languages?: string[] | null
          unlocked_audio?: boolean
          user_agent?: string | null
        }
        Update: {
          catalogue_size?: string | null
          company?: string | null
          created_at?: string
          email?: string
          handled?: boolean
          handled_at?: string | null
          id?: string
          message?: string | null
          name?: string
          referrer?: string | null
          rel_owner?: string | null
          rel_status?: string | null
          role?: string
          source?: string | null
          target_languages?: string[] | null
          unlocked_audio?: boolean
          user_agent?: string | null
        }
        Relationships: []
      }
      job_feedback: {
        Row: {
          created_at: string
          id: string
          job_id: string
          note: string | null
          rating: string
          tags: string[]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          job_id: string
          note?: string | null
          rating: string
          tags?: string[]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          job_id?: string
          note?: string | null
          rating?: string
          tags?: string[]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_feedback_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          company: string | null
          created_at: string
          id: string
          licence_terms_version: string | null
          name: string | null
          product_emails: boolean
          rating_reminders: boolean
          retired_at: string | null
          role: string | null
          stripe_customer_id: string | null
          welcomed_at: string | null
        }
        Insert: {
          company?: string | null
          created_at?: string
          id: string
          licence_terms_version?: string | null
          name?: string | null
          product_emails?: boolean
          rating_reminders?: boolean
          retired_at?: string | null
          role?: string | null
          stripe_customer_id?: string | null
          welcomed_at?: string | null
        }
        Update: {
          company?: string | null
          created_at?: string
          id?: string
          licence_terms_version?: string | null
          name?: string | null
          product_emails?: boolean
          rating_reminders?: boolean
          retired_at?: string | null
          role?: string | null
          stripe_customer_id?: string | null
          welcomed_at?: string | null
        }
        Relationships: []
      }
      song_credits: {
        Row: {
          created_at: string
          delta: number
          id: string
          job_id: string | null
          reason: string
          stripe_event_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          delta: number
          id?: string
          job_id?: string | null
          reason: string
          stripe_event_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          delta?: number
          id?: string
          job_id?: string | null
          reason?: string
          stripe_event_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "song_credits_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      song_job_assets: {
        Row: {
          artist_name: string | null
          bytes: number
          created_at: string
          filename: string
          id: string
          job_id: string
          kind: string
          part: string | null
          path: string
          purged_at: string | null
          user_id: string
        }
        Insert: {
          artist_name?: string | null
          bytes: number
          created_at?: string
          filename: string
          id?: string
          job_id: string
          kind: string
          part?: string | null
          path: string
          purged_at?: string | null
          user_id: string
        }
        Update: {
          artist_name?: string | null
          bytes?: number
          created_at?: string
          filename?: string
          id?: string
          job_id?: string
          kind?: string
          part?: string | null
          path?: string
          purged_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "song_job_assets_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      song_job_deliveries: {
        Row: {
          bytes: number
          created_at: string
          filename: string
          id: string
          job_id: string
          kind: string
          path: string
          purged_at: string | null
          user_id: string
          watermark_id: number | null
        }
        Insert: {
          bytes: number
          created_at?: string
          filename: string
          id?: string
          job_id: string
          kind?: string
          path: string
          purged_at?: string | null
          user_id: string
          watermark_id?: number | null
        }
        Update: {
          bytes?: number
          created_at?: string
          filename?: string
          id?: string
          job_id?: string
          kind?: string
          path?: string
          purged_at?: string | null
          user_id?: string
          watermark_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "song_job_deliveries_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      song_jobs: {
        Row: {
          approved_at: string | null
          claimed_at: string | null
          claimed_by: string | null
          contract_version: number
          copyright_check: Json | null
          created_at: string
          delivered_at: string | null
          delivery_profile: Database["public"]["Enums"]["song_job_delivery_profile"]
          door1_due_on: string | null
          door1_enquiry_id: string | null
          door1_settings: Json
          door1_source_url: string | null
          id: string
          internal_notes: string | null
          licence_terms_version: string | null
          lyrics: string | null
          notes: string | null
          parent_job_id: string | null
          pipeline_error: string | null
          pipeline_state:
            | Database["public"]["Enums"]["song_job_pipeline_state"]
            | null
          pipeline_voice_model: string | null
          primary_artist: string
          quota_consumed_at: string | null
          reroll_index: number
          rights_terms_version: string | null
          rights_warranted_at: string
          route: Database["public"]["Enums"]["song_job_route"]
          seed: number | null
          source_language: string
          status: string
          target_language: string
          title: string
          user_id: string
          voice_id: string | null
          voice_preference: string | null
        }
        Insert: {
          approved_at?: string | null
          claimed_at?: string | null
          claimed_by?: string | null
          contract_version?: number
          copyright_check?: Json | null
          created_at?: string
          delivered_at?: string | null
          delivery_profile?: Database["public"]["Enums"]["song_job_delivery_profile"]
          door1_due_on?: string | null
          door1_enquiry_id?: string | null
          door1_settings?: Json
          door1_source_url?: string | null
          id?: string
          internal_notes?: string | null
          licence_terms_version?: string | null
          lyrics?: string | null
          notes?: string | null
          parent_job_id?: string | null
          pipeline_error?: string | null
          pipeline_state?:
            | Database["public"]["Enums"]["song_job_pipeline_state"]
            | null
          pipeline_voice_model?: string | null
          primary_artist: string
          quota_consumed_at?: string | null
          reroll_index?: number
          rights_terms_version?: string | null
          rights_warranted_at?: string
          route?: Database["public"]["Enums"]["song_job_route"]
          seed?: number | null
          source_language: string
          status?: string
          target_language: string
          title: string
          user_id: string
          voice_id?: string | null
          voice_preference?: string | null
        }
        Update: {
          approved_at?: string | null
          claimed_at?: string | null
          claimed_by?: string | null
          contract_version?: number
          copyright_check?: Json | null
          created_at?: string
          delivered_at?: string | null
          delivery_profile?: Database["public"]["Enums"]["song_job_delivery_profile"]
          door1_due_on?: string | null
          door1_enquiry_id?: string | null
          door1_settings?: Json
          door1_source_url?: string | null
          id?: string
          internal_notes?: string | null
          licence_terms_version?: string | null
          lyrics?: string | null
          notes?: string | null
          parent_job_id?: string | null
          pipeline_error?: string | null
          pipeline_state?:
            | Database["public"]["Enums"]["song_job_pipeline_state"]
            | null
          pipeline_voice_model?: string | null
          primary_artist?: string
          quota_consumed_at?: string | null
          reroll_index?: number
          rights_terms_version?: string | null
          rights_warranted_at?: string
          route?: Database["public"]["Enums"]["song_job_route"]
          seed?: number | null
          source_language?: string
          status?: string
          target_language?: string
          title?: string
          user_id?: string
          voice_id?: string | null
          voice_preference?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "song_jobs_door1_enquiry_id_fkey"
            columns: ["door1_enquiry_id"]
            isOneToOne: false
            referencedRelation: "enquiries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_jobs_parent_job_id_fkey"
            columns: ["parent_job_id"]
            isOneToOne: false
            referencedRelation: "song_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_jobs_voice_id_fkey"
            columns: ["voice_id"]
            isOneToOne: false
            referencedRelation: "voice_models"
            referencedColumns: ["id"]
          },
        ]
      }
      stripe_events: {
        Row: {
          id: string
          processed_at: string | null
          received_at: string
          type: string
        }
        Insert: {
          id: string
          processed_at?: string | null
          received_at?: string
          type: string
        }
        Update: {
          id?: string
          processed_at?: string | null
          received_at?: string
          type?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          id: string
          status: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          tier: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          tier?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          tier?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      voice_models: {
        Row: {
          approved_at: string | null
          artist_name: string
          consent_terms_version: string | null
          consent_warranted_at: string
          created_at: string
          id: string
          internal_notes: string | null
          notes: string | null
          pipeline_voice_model: string | null
          status: string
          training_error: string | null
          user_id: string
        }
        Insert: {
          approved_at?: string | null
          artist_name: string
          consent_terms_version?: string | null
          consent_warranted_at?: string
          created_at?: string
          id?: string
          internal_notes?: string | null
          notes?: string | null
          pipeline_voice_model?: string | null
          status?: string
          training_error?: string | null
          user_id: string
        }
        Update: {
          approved_at?: string | null
          artist_name?: string
          consent_terms_version?: string | null
          consent_warranted_at?: string
          created_at?: string
          id?: string
          internal_notes?: string | null
          notes?: string | null
          pipeline_voice_model?: string | null
          status?: string
          training_error?: string | null
          user_id?: string
        }
        Relationships: []
      }
      voice_samples: {
        Row: {
          bytes: number
          created_at: string
          filename: string
          id: string
          path: string
          seconds: number | null
          user_id: string
          voice_id: string
        }
        Insert: {
          bytes: number
          created_at?: string
          filename: string
          id?: string
          path: string
          seconds?: number | null
          user_id: string
          voice_id: string
        }
        Update: {
          bytes?: number
          created_at?: string
          filename?: string
          id?: string
          path?: string
          seconds?: number | null
          user_id?: string
          voice_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "voice_samples_voice_id_fkey"
            columns: ["voice_id"]
            isOneToOne: false
            referencedRelation: "voice_models"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_heartbeat: {
        Row: {
          seen_at: string
          version: string | null
          worker: string
        }
        Insert: {
          seen_at?: string
          version?: string | null
          worker: string
        }
        Update: {
          seen_at?: string
          version?: string | null
          worker?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_song_job: {
        Args: { p_job_id: string; p_worker: string }
        Returns: boolean
      }
      next_queued_song_job: {
        Args: never
        Returns: {
          approved_at: string | null
          claimed_at: string | null
          claimed_by: string | null
          contract_version: number
          copyright_check: Json | null
          created_at: string
          delivered_at: string | null
          delivery_profile: Database["public"]["Enums"]["song_job_delivery_profile"]
          door1_due_on: string | null
          door1_enquiry_id: string | null
          door1_settings: Json
          door1_source_url: string | null
          id: string
          internal_notes: string | null
          licence_terms_version: string | null
          lyrics: string | null
          notes: string | null
          parent_job_id: string | null
          pipeline_error: string | null
          pipeline_state:
            | Database["public"]["Enums"]["song_job_pipeline_state"]
            | null
          pipeline_voice_model: string | null
          primary_artist: string
          quota_consumed_at: string | null
          reroll_index: number
          rights_terms_version: string | null
          rights_warranted_at: string
          route: Database["public"]["Enums"]["song_job_route"]
          seed: number | null
          source_language: string
          status: string
          target_language: string
          title: string
          user_id: string
          voice_id: string | null
          voice_preference: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "song_jobs"
          isOneToOne: false
          isSetofReturn: true
        }
      }
    }
    Enums: {
      song_job_delivery_profile: "door2" | "door1"
      song_job_pipeline_state:
        | "queued"
        | "claimed"
        | "rendered_local"
        | "delivered"
        | "failed"
        | "blocked"
      song_job_route: "auto" | "door1"
      song_job_status:
        | "submitted"
        | "approved"
        | "in_progress"
        | "delivered"
        | "rejected"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      song_job_delivery_profile: ["door2", "door1"],
      song_job_pipeline_state: [
        "queued",
        "claimed",
        "rendered_local",
        "delivered",
        "failed",
        "blocked",
      ],
      song_job_route: ["auto", "door1"],
      song_job_status: [
        "submitted",
        "approved",
        "in_progress",
        "delivered",
        "rejected",
      ],
    },
  },
} as const
