import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

/**
 * `docs/emails/mockups/<slug>.html`, generated by `scripts/build-email-mockups.mjs`, one file per
 * row in `docs/emails/README.md`. This does not regenerate them (that needs `tsx`, a dev-only
 * tool this suite should not depend on); it pins that the committed files exist, are real HTML
 * with the right `<title>`, and cover every slug the README promises, so a mockup going stale or
 * silently disappearing fails the suite rather than only being noticed when someone opens the
 * folder.
 */

const SLUGS_AND_SUBJECTS: [string, string][] = [
  ['welcome', 'lyrical: your studio is open'],
  ['plan-confirmed', 'lyrical: Plus is confirmed'],
  ['track-delivered', 'lyrical: Midnight City is ready'],
  ['reroll-delivered', 'lyrical: Take 2 of Midnight City is ready'],
  ['track-not-made', 'lyrical: Midnight City did not come out right'],
  ['eoi-received', 'lyrical: we have your enquiry'],
  ['enquiry-received', 'lyrical: we have your enquiry'],
  ['rating-reminder', 'lyrical: how did Midnight City turn out?'],
]

describe('the email mockup set', () => {
  it('has exactly the eight slugs docs/emails/README.md lists, no more, no fewer', () => {
    expect(SLUGS_AND_SUBJECTS.map(([slug]) => slug).sort()).toEqual(
      [
        'welcome',
        'plan-confirmed',
        'track-delivered',
        'reroll-delivered',
        'track-not-made',
        'eoi-received',
        'enquiry-received',
        'rating-reminder',
      ].sort(),
    )
  })

  for (const [slug, subject] of SLUGS_AND_SUBJECTS) {
    it(`${slug}.html exists, is real HTML, and titles itself with the subject line`, () => {
      const path = `docs/emails/mockups/${slug}.html`
      expect(existsSync(path), `${path} is missing; run scripts/build-email-mockups.mjs`).toBe(true)
      const contents = readFileSync(path, 'utf8')
      expect(contents.toLowerCase()).toContain('<!doctype html>')
      expect(contents).toContain(`<title>${subject}</title>`)
      expect(contents).not.toContain('—')
    })
  }
})
