import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/next'
import { fraunces, archivo } from '@/lib/fonts'
import { Nav } from '@/components/Nav'
import { Footer } from '@/components/Footer'
import { SmoothScroll } from '@/components/SmoothScroll'
import './globals.css'
import { SITE_DESCRIPTION as DESCRIPTION, SITE_URL as SITE } from '@/lib/site'
import { ldJson, organizationLd, websiteLd } from '@/lib/structured-data'

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    /*
      The keyword leads, on Henry's instruction 2026-08-09.

      ⚠️ This is one of the FOUR places the locked tagline appears, and the tagline is no
      longer in it. The other three, the hero, the footer and the confirmation email, still
      carry it. Google gives roughly sixty characters here and spends them left to right, so
      a title opening "lyrical |" spends the most valuable space on a word nobody searches.
    */
    default: 'AI music translation, in the artist’s own voice | lyrical',
    template: '%s | lyrical',
  },
  description: DESCRIPTION,
  // Relative, so every route resolves against `metadataBase` and a preview deployment
  // cannot advertise the production URL as its own canonical.
  alternates: { canonical: '/' },
  openGraph: {
    title: 'AI music translation, in the artist’s own voice | lyrical',
    description: DESCRIPTION,
    type: 'website',
    url: SITE,
    siteName: 'lyrical',
    // Without this every shared link, including the one about to go on LinkedIn, renders as
    // a bare grey card. Generated by `scripts/build-social-images.mjs` from the same mark
    // geometry and fonts the site uses, so it cannot drift.
    images: [{ url: '/og.png', width: 1200, height: 630, alt: 'lyrical' }],
  },
  twitter: { card: 'summary_large_image', images: ['/og.png'] },
  robots: { index: true, follow: true },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // suppressHydrationWarning: the inline script below adds `js-motion` to this element
    // before React hydrates, so the server and client class attributes legitimately differ.
    // It applies to this element's own attributes only, not to any children.
    <html
      lang="en"
      className={`${fraunces.variable} ${archivo.variable} h-full`}
      suppressHydrationWarning
    >
      <head>
        {/*
          Opt in to reveal animations before first paint. If JS is disabled this never
          runs, the class is absent, and every section renders plainly visible — which is
          exactly the desired fallback. Kept inline and tiny so there is no flash.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js-motion')}}catch(e){}",
          }}
        />
        {/*
          Structured data. This is the one thing on the page that tells a crawler "lyrical"
          is a company and not an adjective, and that it is the same entity as "lyrical
          Global". See lib/structured-data.ts for what it deliberately does not claim.
        */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: ldJson(organizationLd(SITE), websiteLd(SITE)) }}
        />
      </head>
      <body className="flex min-h-full flex-col">
        <SmoothScroll />
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:bg-indigo focus:px-4 focus:py-2 focus:text-cream"
        >
          Skip to content
        </a>
        <Nav />
        <main id="main" className="flex-1">
          {children}
        </main>
        <Footer />
        {/*
          Vercel Web Analytics. Cookieless and IP-anonymising, so it needs no consent banner,
          which matters on a page whose whole argument is that it handles other people's
          property carefully. It records nothing in development.
        */}
        <Analytics />
      </body>
    </html>
  )
}
