import { toPath } from '@/lib/mark'
import { APPROX } from '@/lib/mark-states'

/**
 * The lyrical mark, alive when the studio is working. Ported from the staff dashboard's
 * `WaveMark.tsx` (lyrical-studio), with one change forced by this site's motion rule: the
 * dashboard morphs the path data every frame, this one animates transform and opacity only.
 *
 * At rest it is the exact brand logo: the two ribbons generated by `lib/mark.ts`, the same
 * geometry every other mark on the site uses. When `active`, the brand ribbons fade out and a
 * matching pair of travelling-wave bands fades in. Each band is two sine periods wide, drawn
 * inside a nested viewport exactly the width of one period, and slides sideways by one period
 * on a loop, so the crests visibly roll through the glyph and the loop point is invisible.
 * Reduced motion keeps the brand ribbons still; the state is also carried by `data-animated`.
 *
 * Server-renderable: no hooks, the animation is CSS in `app/studio/studio.css`.
 */
const TOP_WAVE_PATH = toPath(APPROX.top)
const BOTTOM_WAVE_PATH = toPath(APPROX.bottom)

/** Same band geometry as the dashboard: one period spans the mark's width, x 7..57. */
const WAVE = { x0: 7, x1: 57, amp: 9, thick: 3.6, samples: 44 } as const
const TOP_CENTER = 20
const BOTTOM_CENTER = 44
/** How many periods the band covers. Two, so a one-period slide loops seamlessly. */
const PERIODS = 2

function waveBand(centerY: number): string {
  const { x0, x1, amp, thick, samples } = WAVE
  const period = x1 - x0
  const k = (2 * Math.PI) / period
  const end = x0 + period * PERIODS
  const count = samples * PERIODS
  const centreAt = (x: number) => centerY + amp * Math.sin(k * (x - x0))
  const step = (end - x0) / count
  const f = (v: number) => v.toFixed(2)

  let d = ''
  for (let i = 0; i <= count; i += 1) {
    const x = x0 + i * step
    d += `${i === 0 ? 'M' : 'L'}${f(x)} ${f(centreAt(x) - thick)} `
  }
  for (let i = count; i >= 0; i -= 1) {
    const x = x0 + i * step
    d += `L${f(x)} ${f(centreAt(x) + thick)} `
  }
  return `${d}Z`
}

const TOP_BAND = waveBand(TOP_CENTER)
const BOTTOM_BAND = waveBand(BOTTOM_CENTER)

export type WaveMarkTone = 'accent' | 'ink' | 'indigo' | 'cream'

const TONE_CLASS: Record<WaveMarkTone, string> = {
  accent: 'text-dark-accent',
  ink: 'text-dark-ink',
  indigo: 'text-indigo',
  cream: 'text-cream',
}

export function WaveMark({
  active,
  size = 28,
  tone = 'accent',
  title = 'lyrical',
  className = '',
}: {
  /** Whether something is being made. Drives the travelling wave. */
  active: boolean
  /** Pixel size of the square mark. */
  size?: number
  /** Fill token. Indigo is for cream surfaces only, never the dark ground. */
  tone?: WaveMarkTone
  /** aria-label for the mark. */
  title?: string
  className?: string
}) {
  return (
    <svg
      viewBox="0 0 64 64"
      width={size}
      height={size}
      role="img"
      aria-label={title}
      data-animated={active ? 'true' : 'false'}
      className={`studio-wave shrink-0 ${TONE_CLASS[tone]} ${className}`.trim()}
    >
      <path data-brand-ribbon="top" d={TOP_WAVE_PATH} fill="currentColor" />
      <path data-brand-ribbon="bottom" d={BOTTOM_WAVE_PATH} fill="currentColor" />
      {/*
        A nested viewport one period wide. Anything the band draws beyond x 7..57 is outside
        it and never paints, which is what lets a two-period band slide without a clip path.
      */}
      <svg x={WAVE.x0} y={0} width={WAVE.x1 - WAVE.x0} height={64} viewBox={`${WAVE.x0} 0 ${WAVE.x1 - WAVE.x0} 64`}>
        <g className="studio-wave-travel">
          <path data-wave-ribbon="top" d={TOP_BAND} fill="currentColor" />
          <path data-wave-ribbon="bottom" d={BOTTOM_BAND} fill="currentColor" />
        </g>
      </svg>
    </svg>
  )
}
