// Regenerates the typed contract from the LOCAL Supabase stack (never production).
//
//   npm run db:types          write lib/db/database.types.ts and supabase/generated/contract.py
//   npm run db:types -- --check   exit 1 if the committed files differ from a fresh generation
//
// Both files come straight from the Supabase CLI (`supabase gen types`, TypeScript and Python),
// with a header added and line endings normalised to LF. Never edit them by hand: change a
// migration, `npx supabase db reset`, then run this.
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { connect } from 'node:net'

export const TS_PATH = 'lib/db/database.types.ts'
export const PY_PATH = 'supabase/generated/contract.py'
const LOCAL_DB = { host: '127.0.0.1', port: 54322 }

const TS_HEADER = [
  '// GENERATED by `npm run db:types` (supabase gen types typescript --local). Do not edit.',
  '// Source of truth: supabase/migrations. Human page: docs/CONTRACT.md.',
  '',
].join('\n')
const PY_HEADER = [
  '# GENERATED by `npm run db:types` in lyrical-website (supabase gen types --lang python --local).',
  '# Do not edit. Source of truth: supabase/migrations. Human page: docs/CONTRACT.md.',
  '# Copied into the render worker repo as-is.',
  '',
].join('\n')

function supabase(args: string[]): string {
  // One command string through the shell, so Windows resolves the npm .cmd shim the same way a
  // terminal does. Every argument is a constant in this file, never input.
  return execSync(['npx', 'supabase', ...args].join(' '), {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    maxBuffer: 32 * 1024 * 1024,
  })
}

const lf = (s: string) => s.replace(/\r\n/g, '\n').replace(/\s*$/, '\n')

/** Fresh output for both files, from the local stack. Throws (loud) if the CLI fails. */
export function generate(): { ts: string; py: string } {
  const ts = supabase(['gen', 'types', 'typescript', '--local', '--schema', 'public'])
  const py = supabase(['gen', 'types', '--lang', 'python', '--local', '--schema', 'public'])
  if (!ts.includes('export type Database')) throw new Error('supabase gen types (typescript) returned no Database type')
  if (!py.includes('class PublicSongJobs')) throw new Error('supabase gen types (python) returned no PublicSongJobs')
  return { ts: TS_HEADER + lf(ts), py: PY_HEADER + lf(py) }
}

/** True when something is listening on the local stack's Postgres port. */
export function localStackUp(timeoutMs = 1500): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = connect(LOCAL_DB)
    const done = (up: boolean) => {
      socket.destroy()
      resolve(up)
    }
    socket.setTimeout(timeoutMs, () => done(false))
    socket.once('connect', () => done(true))
    socket.once('error', () => done(false))
  })
}

async function main() {
  if (!(await localStackUp())) {
    throw new Error('the local Supabase stack is not running: `npx supabase start` first')
  }
  const fresh = generate()
  const check = process.argv.includes('--check')
  let drift = false
  for (const [path, text] of [[TS_PATH, fresh.ts], [PY_PATH, fresh.py]] as const) {
    if (check) {
      let committed = ''
      try {
        committed = readFileSync(path, 'utf8').replace(/\r\n/g, '\n')
      } catch {
        // missing counts as drift
      }
      if (committed !== text) {
        drift = true
        console.error(`DRIFT ${path}: regenerate with npm run db:types`)
      } else console.log(`ok    ${path}`)
    } else {
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(path, text)
      console.log(`wrote ${path}`)
    }
  }
  if (drift) process.exit(1)
}

if (process.argv[1] && /db-types\.ts$/.test(process.argv[1])) {
  main().catch((e) => {
    console.error(e instanceof Error ? e.message : e)
    process.exit(1)
  })
}
