-- Baseline pulled from production (hikvjnpkvnxibfzdnpig) with `supabase db pull` on 2026-09-24.
-- Generated by the CLI, then edited in exactly four places, each marked "Baseline edit":
--   1. the song-job-emails webhook trigger is removed (it embeds a secret),
--   2. the storage buckets are appended (db pull captures schema, not bucket rows),
--   3. a Realtime-owned trigger is removed (the Realtime service creates it itself), and
--   4. the trailing table REVOKEs are moved before the GRANTs (else column grants are lost).
-- Production already records this version as applied in supabase_migrations.schema_migrations.




SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."crm_issues" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" "uuid",
    "user_id" "uuid",
    "kind" "text" NOT NULL,
    "status" "text" DEFAULT 'open'::"text" NOT NULL,
    "detail" "text",
    "resolved_at" timestamp with time zone,
    CONSTRAINT "crm_issues_status_check" CHECK (("status" = ANY (ARRAY['open'::"text", 'ack'::"text", 'resolved'::"text"])))
);


ALTER TABLE "public"."crm_issues" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."crm_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "author" "text",
    "user_id" "uuid",
    "enquiry_id" "uuid",
    "body" "text" NOT NULL,
    CONSTRAINT "crm_notes_target" CHECK ((("user_id" IS NOT NULL) OR ("enquiry_id" IS NOT NULL)))
);


ALTER TABLE "public"."crm_notes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."crm_tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "enquiry_id" "uuid",
    "title" "text" NOT NULL,
    "due_on" "date",
    "owner" "text",
    "done_at" timestamp with time zone
);


ALTER TABLE "public"."crm_tasks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."email_log" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "sent_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "to_email" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "job_id" "uuid",
    "provider_id" "text"
);


ALTER TABLE "public"."email_log" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."enquiries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "role" "text" NOT NULL,
    "company" "text",
    "catalogue_size" "text",
    "target_languages" "text"[],
    "message" "text",
    "source" "text",
    "unlocked_audio" boolean DEFAULT false NOT NULL,
    "user_agent" "text",
    "referrer" "text",
    "handled" boolean DEFAULT false NOT NULL,
    "handled_at" timestamp with time zone,
    "rel_status" "text",
    "rel_owner" "text",
    CONSTRAINT "enquiries_rel_status_check" CHECK (("rel_status" = ANY (ARRAY['new'::"text", 'contacted'::"text", 'in_talks'::"text", 'signed'::"text", 'closed'::"text"])))
);


ALTER TABLE "public"."enquiries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."job_feedback" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "rating" "text" NOT NULL,
    "note" "text",
    "tags" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    CONSTRAINT "job_feedback_down_needs_note" CHECK ((("rating" <> 'down'::"text") OR ("length"("btrim"(COALESCE("note", ''::"text"))) >= 20))),
    CONSTRAINT "job_feedback_rating_check" CHECK (("rating" = ANY (ARRAY['up'::"text", 'down'::"text"])))
);


ALTER TABLE "public"."job_feedback" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "company" "text",
    "role" "text",
    "stripe_customer_id" "text",
    "licence_terms_version" "text",
    "welcomed_at" timestamp with time zone,
    "product_emails" boolean DEFAULT true NOT NULL,
    "rating_reminders" boolean DEFAULT true NOT NULL,
    "retired_at" timestamp with time zone
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."song_credits" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "delta" integer NOT NULL,
    "reason" "text" NOT NULL,
    "job_id" "uuid",
    "stripe_event_id" "text",
    CONSTRAINT "song_credits_reason_check" CHECK (("reason" = ANY (ARRAY['purchase_single'::"text", 'consume'::"text", 'refund'::"text", 'grant'::"text"])))
);


ALTER TABLE "public"."song_credits" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."song_job_assets" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "kind" "text" NOT NULL,
    "artist_name" "text",
    "path" "text" NOT NULL,
    "filename" "text" NOT NULL,
    "bytes" bigint NOT NULL,
    "part" "text",
    "purged_at" timestamp with time zone
);


ALTER TABLE "public"."song_job_assets" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."song_job_deliveries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "kind" "text" DEFAULT 'cover'::"text" NOT NULL,
    "path" "text" NOT NULL,
    "filename" "text" NOT NULL,
    "bytes" bigint NOT NULL,
    "watermark_id" integer,
    "purged_at" timestamp with time zone
);


ALTER TABLE "public"."song_job_deliveries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."song_jobs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "primary_artist" "text" NOT NULL,
    "source_language" "text" NOT NULL,
    "target_language" "text" NOT NULL,
    "notes" "text",
    "status" "text" DEFAULT 'submitted'::"text" NOT NULL,
    "rights_warranted_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "approved_at" timestamp with time zone,
    "delivered_at" timestamp with time zone,
    "internal_notes" "text",
    "lyrics" "text",
    "voice_id" "uuid",
    "voice_preference" "text",
    "rights_terms_version" "text",
    "pipeline_state" "text",
    "pipeline_voice_model" "text",
    "pipeline_error" "text",
    "quota_consumed_at" timestamp with time zone,
    "route" "text" DEFAULT 'auto'::"text" NOT NULL,
    "parent_job_id" "uuid",
    "reroll_index" smallint DEFAULT 0 NOT NULL,
    "seed" integer,
    "licence_terms_version" "text",
    "delivery_profile" "text" DEFAULT 'door2'::"text" NOT NULL,
    "copyright_check" "jsonb",
    "door1_enquiry_id" "uuid",
    "door1_source_url" "text",
    "door1_settings" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "door1_due_on" "date",
    CONSTRAINT "song_jobs_delivery_profile_check" CHECK (("delivery_profile" = ANY (ARRAY['door2'::"text", 'door1'::"text"])))
);


ALTER TABLE "public"."song_jobs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stripe_events" (
    "id" "text" NOT NULL,
    "type" "text" NOT NULL,
    "received_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "processed_at" timestamp with time zone
);


ALTER TABLE "public"."stripe_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "stripe_customer_id" "text",
    "stripe_subscription_id" "text",
    "tier" "text",
    "status" "text" DEFAULT 'incomplete'::"text" NOT NULL,
    "current_period_start" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    CONSTRAINT "subscriptions_tier_check" CHECK (("tier" = ANY (ARRAY['fan'::"text", 'superfan'::"text", 'starter'::"text", 'creator'::"text", 'pro'::"text"])))
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."voice_models" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "artist_name" "text" NOT NULL,
    "status" "text" DEFAULT 'collecting'::"text" NOT NULL,
    "notes" "text",
    "consent_warranted_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "approved_at" timestamp with time zone,
    "internal_notes" "text",
    "consent_terms_version" "text",
    "pipeline_voice_model" "text",
    "training_error" "text"
);


ALTER TABLE "public"."voice_models" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."voice_samples" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "voice_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "path" "text" NOT NULL,
    "filename" "text" NOT NULL,
    "bytes" bigint NOT NULL,
    "seconds" numeric
);


ALTER TABLE "public"."voice_samples" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."worker_heartbeat" (
    "worker" "text" NOT NULL,
    "seen_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "version" "text"
);


ALTER TABLE "public"."worker_heartbeat" OWNER TO "postgres";


ALTER TABLE ONLY "public"."crm_issues"
    ADD CONSTRAINT "crm_issues_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."crm_notes"
    ADD CONSTRAINT "crm_notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."crm_tasks"
    ADD CONSTRAINT "crm_tasks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."email_log"
    ADD CONSTRAINT "email_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."enquiries"
    ADD CONSTRAINT "enquiries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."job_feedback"
    ADD CONSTRAINT "job_feedback_job_id_user_id_key" UNIQUE ("job_id", "user_id");



ALTER TABLE ONLY "public"."job_feedback"
    ADD CONSTRAINT "job_feedback_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_stripe_customer_id_key" UNIQUE ("stripe_customer_id");



ALTER TABLE ONLY "public"."song_credits"
    ADD CONSTRAINT "song_credits_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."song_credits"
    ADD CONSTRAINT "song_credits_stripe_event_id_key" UNIQUE ("stripe_event_id");



ALTER TABLE ONLY "public"."song_job_assets"
    ADD CONSTRAINT "song_job_assets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."song_job_deliveries"
    ADD CONSTRAINT "song_job_deliveries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."song_jobs"
    ADD CONSTRAINT "song_jobs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stripe_events"
    ADD CONSTRAINT "stripe_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_stripe_subscription_id_key" UNIQUE ("stripe_subscription_id");



ALTER TABLE ONLY "public"."voice_models"
    ADD CONSTRAINT "voice_models_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."voice_samples"
    ADD CONSTRAINT "voice_samples_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."worker_heartbeat"
    ADD CONSTRAINT "worker_heartbeat_pkey" PRIMARY KEY ("worker");



CREATE INDEX "crm_issues_status_idx" ON "public"."crm_issues" USING "btree" ("status", "created_at" DESC);



CREATE INDEX "crm_notes_enquiry_idx" ON "public"."crm_notes" USING "btree" ("enquiry_id", "created_at" DESC);



CREATE INDEX "crm_notes_user_idx" ON "public"."crm_notes" USING "btree" ("user_id", "created_at" DESC);



CREATE INDEX "crm_tasks_open_idx" ON "public"."crm_tasks" USING "btree" ("done_at", "due_on");



CREATE INDEX "email_log_slug_idx" ON "public"."email_log" USING "btree" ("slug", "sent_at" DESC);



CREATE INDEX "email_log_user_idx" ON "public"."email_log" USING "btree" ("user_id", "sent_at" DESC);



CREATE INDEX "enquiries_created_at_idx" ON "public"."enquiries" USING "btree" ("created_at" DESC);



CREATE INDEX "enquiries_handled_idx" ON "public"."enquiries" USING "btree" ("handled", "created_at" DESC);



CREATE INDEX "job_feedback_created_idx" ON "public"."job_feedback" USING "btree" ("created_at" DESC);



CREATE INDEX "song_credits_user_idx" ON "public"."song_credits" USING "btree" ("user_id", "created_at" DESC);



CREATE INDEX "song_job_assets_job_idx" ON "public"."song_job_assets" USING "btree" ("job_id");



CREATE INDEX "song_job_deliveries_job_idx" ON "public"."song_job_deliveries" USING "btree" ("job_id");



CREATE INDEX "song_jobs_parent_idx" ON "public"."song_jobs" USING "btree" ("parent_job_id");



CREATE INDEX "song_jobs_pipeline_state_idx" ON "public"."song_jobs" USING "btree" ("pipeline_state") WHERE ("pipeline_state" IS NOT NULL);



CREATE INDEX "song_jobs_quota_consumed_idx" ON "public"."song_jobs" USING "btree" ("user_id", "quota_consumed_at") WHERE ("quota_consumed_at" IS NOT NULL);



CREATE INDEX "song_jobs_status_idx" ON "public"."song_jobs" USING "btree" ("status", "created_at" DESC);



CREATE INDEX "song_jobs_user_idx" ON "public"."song_jobs" USING "btree" ("user_id", "created_at" DESC);



CREATE UNIQUE INDEX "subscriptions_user_id_key" ON "public"."subscriptions" USING "btree" ("user_id");



CREATE UNIQUE INDEX "subscriptions_user_idx" ON "public"."subscriptions" USING "btree" ("user_id");



CREATE INDEX "voice_models_status_idx" ON "public"."voice_models" USING "btree" ("status", "created_at" DESC);



CREATE INDEX "voice_models_user_idx" ON "public"."voice_models" USING "btree" ("user_id", "created_at" DESC);



CREATE INDEX "voice_samples_voice_idx" ON "public"."voice_samples" USING "btree" ("voice_id");



-- Baseline edit 1. The "song-job-emails" Database Webhook (AFTER UPDATE ON public.song_jobs, POST to the studio
-- /api/hooks/song-job with an x-hook-secret header) exists in production but is NOT reproduced
-- here: its definition carries the hook secret in plain text and this repository is public.
-- It is managed in the Supabase dashboard (Database > Webhooks). See docs/CONTRACT.md.



ALTER TABLE ONLY "public"."crm_issues"
    ADD CONSTRAINT "crm_issues_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."song_jobs"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."crm_issues"
    ADD CONSTRAINT "crm_issues_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."crm_notes"
    ADD CONSTRAINT "crm_notes_enquiry_id_fkey" FOREIGN KEY ("enquiry_id") REFERENCES "public"."enquiries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."crm_notes"
    ADD CONSTRAINT "crm_notes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."crm_tasks"
    ADD CONSTRAINT "crm_tasks_enquiry_id_fkey" FOREIGN KEY ("enquiry_id") REFERENCES "public"."enquiries"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."crm_tasks"
    ADD CONSTRAINT "crm_tasks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."email_log"
    ADD CONSTRAINT "email_log_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."song_jobs"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."email_log"
    ADD CONSTRAINT "email_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."job_feedback"
    ADD CONSTRAINT "job_feedback_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."song_jobs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_feedback"
    ADD CONSTRAINT "job_feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_credits"
    ADD CONSTRAINT "song_credits_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."song_jobs"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."song_credits"
    ADD CONSTRAINT "song_credits_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_job_assets"
    ADD CONSTRAINT "song_job_assets_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."song_jobs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_job_assets"
    ADD CONSTRAINT "song_job_assets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_job_deliveries"
    ADD CONSTRAINT "song_job_deliveries_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."song_jobs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_job_deliveries"
    ADD CONSTRAINT "song_job_deliveries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_jobs"
    ADD CONSTRAINT "song_jobs_door1_enquiry_id_fkey" FOREIGN KEY ("door1_enquiry_id") REFERENCES "public"."enquiries"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."song_jobs"
    ADD CONSTRAINT "song_jobs_parent_job_id_fkey" FOREIGN KEY ("parent_job_id") REFERENCES "public"."song_jobs"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."song_jobs"
    ADD CONSTRAINT "song_jobs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_jobs"
    ADD CONSTRAINT "song_jobs_voice_id_fkey" FOREIGN KEY ("voice_id") REFERENCES "public"."voice_models"("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voice_models"
    ADD CONSTRAINT "voice_models_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voice_samples"
    ADD CONSTRAINT "voice_samples_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voice_samples"
    ADD CONSTRAINT "voice_samples_voice_id_fkey" FOREIGN KEY ("voice_id") REFERENCES "public"."voice_models"("id") ON DELETE CASCADE;



ALTER TABLE "public"."crm_issues" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."crm_notes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."crm_tasks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."email_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."enquiries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_feedback" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "job_feedback_self_insert" ON "public"."job_feedback" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "job_feedback_self_select" ON "public"."job_feedback" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "job_feedback_self_update" ON "public"."job_feedback" FOR UPDATE USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profiles_self_select" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "profiles_self_update" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "profiles_self_upsert" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



ALTER TABLE "public"."song_credits" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "song_credits_self_select" ON "public"."song_credits" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."song_job_assets" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "song_job_assets_own_insert" ON "public"."song_job_assets" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "song_job_assets_own_select" ON "public"."song_job_assets" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."song_job_deliveries" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "song_job_deliveries_own_select" ON "public"."song_job_deliveries" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."song_jobs" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "song_jobs_own_insert" ON "public"."song_jobs" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "user_id") AND ("status" = 'submitted'::"text")));



CREATE POLICY "song_jobs_own_lyrics_update" ON "public"."song_jobs" FOR UPDATE TO "authenticated" USING ((("auth"."uid"() = "user_id") AND ("status" = 'submitted'::"text"))) WITH CHECK ((("auth"."uid"() = "user_id") AND ("status" = 'submitted'::"text")));



CREATE POLICY "song_jobs_own_select" ON "public"."song_jobs" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."stripe_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "subscriptions_own_select" ON "public"."subscriptions" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."voice_models" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "voice_models_own_insert" ON "public"."voice_models" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "voice_models_own_select" ON "public"."voice_models" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."voice_samples" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "voice_samples_own_insert" ON "public"."voice_samples" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "voice_samples_own_select" ON "public"."voice_samples" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."worker_heartbeat" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "worker_heartbeat_read" ON "public"."worker_heartbeat" FOR SELECT USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































-- Baseline edit 4. db pull emitted these table-level REVOKEs at the END of the file, after the
-- column-level GRANTs. A table-level REVOKE also removes the column grants, so replayed in that
-- order the customer column grants on song_jobs vanished. They are moved here, before the
-- GRANTs, which reproduces production exactly (checked against information_schema).
revoke insert on table "public"."song_jobs" from "anon";

revoke select on table "public"."song_jobs" from "anon";

revoke truncate on table "public"."song_jobs" from "anon";

revoke update on table "public"."song_jobs" from "anon";

revoke insert on table "public"."song_jobs" from "authenticated";

revoke select on table "public"."song_jobs" from "authenticated";

revoke truncate on table "public"."song_jobs" from "authenticated";

revoke update on table "public"."song_jobs" from "authenticated";

revoke select on table "public"."voice_models" from "anon";

revoke select on table "public"."voice_models" from "authenticated";


GRANT ALL ON TABLE "public"."crm_issues" TO "anon";
GRANT ALL ON TABLE "public"."crm_issues" TO "authenticated";
GRANT ALL ON TABLE "public"."crm_issues" TO "service_role";



GRANT ALL ON TABLE "public"."crm_notes" TO "anon";
GRANT ALL ON TABLE "public"."crm_notes" TO "authenticated";
GRANT ALL ON TABLE "public"."crm_notes" TO "service_role";



GRANT ALL ON TABLE "public"."crm_tasks" TO "anon";
GRANT ALL ON TABLE "public"."crm_tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."crm_tasks" TO "service_role";



GRANT ALL ON TABLE "public"."email_log" TO "anon";
GRANT ALL ON TABLE "public"."email_log" TO "authenticated";
GRANT ALL ON TABLE "public"."email_log" TO "service_role";



GRANT ALL ON TABLE "public"."enquiries" TO "anon";
GRANT ALL ON TABLE "public"."enquiries" TO "authenticated";
GRANT ALL ON TABLE "public"."enquiries" TO "service_role";



GRANT ALL ON TABLE "public"."job_feedback" TO "anon";
GRANT ALL ON TABLE "public"."job_feedback" TO "authenticated";
GRANT ALL ON TABLE "public"."job_feedback" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."song_credits" TO "anon";
GRANT ALL ON TABLE "public"."song_credits" TO "authenticated";
GRANT ALL ON TABLE "public"."song_credits" TO "service_role";



GRANT ALL ON TABLE "public"."song_job_assets" TO "anon";
GRANT ALL ON TABLE "public"."song_job_assets" TO "authenticated";
GRANT ALL ON TABLE "public"."song_job_assets" TO "service_role";



GRANT ALL ON TABLE "public"."song_job_deliveries" TO "anon";
GRANT ALL ON TABLE "public"."song_job_deliveries" TO "authenticated";
GRANT ALL ON TABLE "public"."song_job_deliveries" TO "service_role";



GRANT REFERENCES,DELETE,TRIGGER,MAINTAIN ON TABLE "public"."song_jobs" TO "anon";
GRANT REFERENCES,DELETE,TRIGGER,MAINTAIN ON TABLE "public"."song_jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."song_jobs" TO "service_role";



GRANT SELECT("id") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("id"),INSERT("id") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("created_at") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("created_at") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("user_id") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("user_id"),INSERT("user_id") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("title") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("title"),INSERT("title") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("primary_artist") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("primary_artist"),INSERT("primary_artist") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("source_language") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("source_language"),INSERT("source_language") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("target_language") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("target_language"),INSERT("target_language") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("notes") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("notes"),INSERT("notes") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("status") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("status"),INSERT("status") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("rights_warranted_at") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("rights_warranted_at") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("approved_at") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("approved_at") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("delivered_at") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("delivered_at") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("lyrics"),INSERT("lyrics"),UPDATE("lyrics") ON TABLE "public"."song_jobs" TO "authenticated";
GRANT SELECT("lyrics") ON TABLE "public"."song_jobs" TO "anon";



GRANT SELECT("voice_id") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("voice_id"),INSERT("voice_id") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("voice_preference") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("voice_preference"),INSERT("voice_preference") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT INSERT("rights_terms_version") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("parent_job_id") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("parent_job_id") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("reroll_index") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("reroll_index") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("licence_terms_version") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("licence_terms_version") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT SELECT("delivery_profile") ON TABLE "public"."song_jobs" TO "anon";
GRANT SELECT("delivery_profile") ON TABLE "public"."song_jobs" TO "authenticated";



GRANT ALL ON TABLE "public"."stripe_events" TO "anon";
GRANT ALL ON TABLE "public"."stripe_events" TO "authenticated";
GRANT ALL ON TABLE "public"."stripe_events" TO "service_role";



GRANT ALL ON TABLE "public"."subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."voice_models" TO "anon";
GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."voice_models" TO "authenticated";
GRANT ALL ON TABLE "public"."voice_models" TO "service_role";



GRANT SELECT("id") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("id") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("created_at") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("created_at") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("user_id") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("user_id") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("artist_name") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("artist_name") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("status") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("status") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("notes") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("notes") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("consent_warranted_at") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("consent_warranted_at") ON TABLE "public"."voice_models" TO "authenticated";



GRANT SELECT("approved_at") ON TABLE "public"."voice_models" TO "anon";
GRANT SELECT("approved_at") ON TABLE "public"."voice_models" TO "authenticated";



GRANT ALL ON TABLE "public"."voice_samples" TO "anon";
GRANT ALL ON TABLE "public"."voice_samples" TO "authenticated";
GRANT ALL ON TABLE "public"."voice_samples" TO "service_role";



GRANT ALL ON TABLE "public"."worker_heartbeat" TO "anon";
GRANT ALL ON TABLE "public"."worker_heartbeat" TO "authenticated";
GRANT ALL ON TABLE "public"."worker_heartbeat" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";









































-- Baseline edit 3. db pull also emitted CREATE TRIGGER tr_check_filters ON realtime.subscription.
-- That object belongs to the Supabase Realtime service, which creates it itself; it is not ours
-- and fails on a stack without Realtime, so it is dropped here.


  create policy "deliveries_own_select"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'deliveries'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "submissions_own_insert"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'submissions'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "submissions_own_select"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'submissions'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "voice_training_own_insert"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'voice-training'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "voice_training_own_select"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'voice-training'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));


-- Baseline edit 2. The storage buckets, as they exist in production (all private, no limits).
-- Object paths and who writes them: docs/CONTRACT.md.
insert into storage.buckets (id, name, public) values
  ('deliveries', 'deliveries', false),
  ('door1', 'door1', false),
  ('listen', 'listen', false),
  ('submissions', 'submissions', false),
  ('voice-training', 'voice-training', false)
on conflict (id) do nothing;
